### ISSUE TITLE
Dont stake with these people 

### ISSUE THREAD

**Issue by Still1995** [terra-money/validator-profiles#510]
They can't even respond to an email been almost a week

**Comment by Jared-TFL** [comment]
You have left this issue 3 times in one week.
You have never stated who you are trying to contact.

**Comment by Still1995** [comment]
I sent an email to the contact email on your page I was trying to
redelegate 1950000 lunc and it undelegated them now they are frozen I want
them released asap not the 21 days I was going to stake a lot more but if
this can't be resolved then I will not be

**Comment by Jared-TFL** [comment]
This is a repo with every validator contact in it.
You are not leaving a comment for one single validator here.
No one who manages this repo runs a validator.
This is like calling up google and complaining that the t-shirt you ordered off threadless has not arrived yet.

So, once more:
Who are you trying to contact?

**Comment by Still1995** [comment]
Orion.money

**Comment by Jared-TFL** [comment]
Here is their Twitter: https://twitter.com/orion_money?s=21&t=sAdbeecjq4-WhAW6UHpovw

They posted there 4 days ago.

Here is their discord: https://discord.gg/5vbWB2PWeS

I'd try one of those. I want to stress that this issue is not related to this GitHub repo, and all I did is put Orion.money into google and copy contact information from their website.

**Comment by Jared-TFL** [comment]
Now, @Still1995 I think your question isn't actually related to Orion.
You are experiencing a chain limitation, which no one is able to change without governance. The 21 day unbonding period is a parameter of the chain.

Since you are looking to make changes on terra classic, I suggest you join this group: https://discord.gg/XXXk8xbZke

**Comment by Jared-TFL** [comment]
I don't get notification about closed issues. So, won't be responding further. Best of luck learning about the Luna classic chain.

**Comment by Still1995** [comment]
Thank you for the information and getting back to me I appreciate it have a
good day
